formatter: "markdown table"
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  ## Example(s)

  ```hcl
  {{ include "./example/basic/main.tf"}}
  ```

output:
  file: README.md
  mode: inject
  template: |-
      <!-- START_TF_DOCS_CONTENT -->
      {{ .Content }}
      <!-- END_TF_DOCS_CONTENT -->