formatter: "markdown table"
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  ## Usage
  Basic usage of this module is as follows:

  ```hcl
  {{ include "./examples/main.tf"}}
  ```

  ## Example(s)

  ```hcl
  {{ include "./main.tf"}}
  ```
output:
  file: README.md
  mode: inject
  template: |-
      <!-- START_TF_DOCS_CONTENT -->
      {{ .Content }}
      <!-- END_TF_DOCS_CONTENT -->